chore(grpc): enhance domain grpc services
iotaledger/identity.rs pull request #1381
Opened 2024-06-18 08:43 UTC by itsyaasir

# Description of change
Please write a summary of your changes and why you made them.

## Links to any relevant issues
Be sure to reference any related issues by adding `fixes issue #`.

## Type of change
Add an `x` to the boxes that are relevant to your changes.

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] Enhancement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Fix

## How the change has been tested
Describe the tests that you ran to verify your changes.
Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist
Add an `x` to the boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-06-20 07:43 UTC, UMR1352 approved these changes
Looking good! Do we really care about the order in which domains are validated? If that's not the case let's validate them parallely

2024-06-20 07:49 UTC, wulfraem requested changes

2024-06-20 07:49 UTC, wulfraem commented on bindings/grpc/src/services/domain_linkage.rs
Most probably bike shedding, I guess, but would it make sense to align the `use` statements and proto file includes a bit? Skimming through the existing service files, we might derive the following rules:

- proto file derived modules should start with "_", e.g.

```rs
#[allow(clippy::module_inception)]
mod _endpoint {
  tonic::include_proto!("endpoint");
}
```

- types from those are imported with the local prefix, **but** sorted into the non-std, non-local imports

The second point is not really beautiful, but ensures, that automatically adding missing imports (e.g. via vscode) don't get added to the "external" block and have to be moved to an internal block below it, and have to be rewritten (in case we'd go for a `self::` or `crate::` prefix).

Open for ideas here, @UMR1352, @itsyaasir. ^^

Just noticed, that we have `use crate` and `use domain_linkages` import leading to the same set of types, so started comparing the other imports a bit. ^^;;

2024-06-20 07:49 UTC, wulfraem commented on examples/1_advanced/6_domain_linkage.rs
> +  let domain_2: Url = Url::parse("https://foo.example.com")?;
Should both domains be identical here?

2024-06-20 15:29 UTC, eike-hass approved these changes

2024-06-21 05:22 UTC, wulfraem approved these changes

2024-06-21 07:20 UTC, merged