Add support for `did:jwk` resolution
iotaledger/identity.rs pull request #1404
Opened 2024-08-30 13:49 UTC by UMR1352

# Description of change
Add support for handling and resolving `did:jwk` DIDs.
WASM bindings included.

## Type of change
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] Enhancement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Fix

## How the change has been tested
e2e and unit tests.

## Change checklist
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-09-03 09:17 UTC, wulfraem requested changes

2024-09-04 07:12 UTC, UMR1352 commented on bindings/wasm/src/did/did_jwk.rs
> +  #[wasm_bindgen]
You don't say 👁️👁️

2024-09-04 07:14 UTC, UMR1352 commented on bindings/wasm/src/did/did_jwk.rs
> +  #[wasm_bindgen]
For now let's keep it like this, but we should open an issue where we remove the `#[wasm_bindgen]` macro whenever it appears without arguments in an impl block that already has that macro applied

2024-09-04 08:01 UTC, wulfraem commented on bindings/wasm/src/did/did_jwk.rs
> +  #[wasm_bindgen]
Created https://github.com/iotaledger/identity.rs/issues/1407 ^^

2024-09-04 08:02 UTC, wulfraem approved these changes

2024-09-05 09:46 UTC, merged