Split MerkleTag into MerkleDigestTag and MerkleSigantureTag
iotaledger/identity.rs pull request #211
Opened 2021-04-17 19:01 UTC by m-renaud

# Description of change

Split the `MerkleTag` type into separate `MerkleDigestTag` and `MerkleSignatureTag` types.

Previously, both signature and digest algorithms were represented with the same tag which didn't provide as much type safety as possible since they could be used interchangeably. Specifically, the `MerkleKey::extract_tags()` function previously returned `(MerkleTag, MerkleTag)` and one would need to look at the docs or implementation to determine which one was the signature and which was the digest which is error prone. Now these have separate types.

This change also revealed a (small) bug in the verifier where the digest tag was returned as part of a signature tag verification error which would have been very confusing.

## Links to any relevant issues

fixes issue #159 

## Type of change

- [x] Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

`cargo test`

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

2021-04-19 15:52 UTC, l1h3r commented on identity-core/src/crypto/merkle_key/verifier.rs
> +    return Err(Error::InvalidMerkleSignatureKeyTag(Some(tag_s)));
💯

2021-04-19 16:00 UTC, l1h3r requested changes

2021-04-20 01:31 UTC, m-renaud commented on bindings/wasm/src/document.rs
> +use identity::crypto::merkle_key::MerkleSignatureTag;
Done.

2021-04-20 01:31 UTC, m-renaud commented on identity-core/src/crypto/merkle_key/verifier.rs
> +    return Err(Error::InvalidMerkleSignatureKeyTag(Some(tag_s)));
😎

2021-04-20 16:16 UTC, l1h3r approved these changes
🚀

2021-04-20 17:13 UTC, merged