Add ability to configure account clients
iotaledger/identity.rs pull request #293
Opened 2021-07-07 05:05 UTC by l1h3r

# Description of change

Adds the ability to configure `Client` instances used by `Account` internals

## Type of change

- [x] Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Examples and tests

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-07 13:16 UTC, PhilippGackstatter requested changes

2021-07-07 13:16 UTC, PhilippGackstatter commented on examples/account/config.rs
> +    .client(Network::Mainnet, |scope| {
It's unclear what `scope` means here. Why not `client_builder` instead?

2021-07-07 13:16 UTC, PhilippGackstatter commented on identity-account/src/account/builder.rs
> +    F: Fn(ClientBuilder) -> ClientBuilder,
I think the more appropriate bound would be `FnOnce`, as we don't call `f` repeatedly.

2021-07-08 06:26 UTC, PhilippGackstatter approved these changes

2021-07-09 12:42 UTC, JelleMillenaar approved these changes

2021-07-09 12:42 UTC, merged